field: 7833bd9a-cf0e-432a-9872-edbb37927a9c # Race Results
fieldLayouts:
  32fd83a0-3d5d-4f16-bff5-a69a34274e25:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 84b9e867-0255-4baf-8bda-84c75000b8ea # Edition
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a66a8cd-a241-40a5-891c-c2db3ae392d3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a2fdf043-706c-497b-baac-9bab8eec24f1 # Link
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9df8ef59-330c-4d03-84b9-f1df2341fab0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 805d5300-4422-4f84-b533-1675ac9edc49
        userCondition: null
fields:
  84b9e867-0255-4baf-8bda-84c75000b8ea: # Edition
    columnSuffix: dzalcpxv
    contentColumnType: text
    fieldGroup: null
    handle: linkText
    instructions: null
    name: Edition
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a2fdf043-706c-497b-baac-9bab8eec24f1: # Link
    columnSuffix: trcxesnu
    contentColumnType: string(255)
    fieldGroup: null
    handle: linkDestination
    instructions: null
    name: Link
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: link
name: Results
sortOrder: 1
