fieldLayouts:
  4f43c1c6-3f09-49e7-9d61-10fbc4cec49e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f0d8b023-4622-4428-b3e3-e75fa9b46c84
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 40aac9d7-9827-49f3-8c21-f3afc8801788 # Common Excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bda1c199-27e7-45f5-bff0-e66836840062
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fa7b64ed-a01d-49d6-ac41-0662e5ccddbe # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 801a7e31-0ab1-43c8-8ce7-c76c2fb8e2b0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bb11d387-7c81-4787-adbd-e6bd9b4dc26a
        userCondition: null
handle: blogs
hasTitleField: true
name: Blogs
section: f51a2162-b4d6-468e-ac97-f65ecbda080c # Blogs
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
