fieldLayouts:
  135d3990-5363-4644-8699-175e4cac7e22:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0544f7ef-9365-4cf1-a2b3-b0d5cd94b229
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f7f27716-4ea7-4461-8c8a-9b450fc114bd # Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 40005212-9e6f-45fb-9339-34c79598112d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 40aac9d7-9827-49f3-8c21-f3afc8801788 # Common Excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 52248b54-9ae3-4f37-9440-a72ba2c51b9a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 33cc00d2-9fab-43dc-8159-86109aec387b # Main Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f91d83a4-0d99-4a95-b366-93ff95149c05
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fa7b64ed-a01d-49d6-ac41-0662e5ccddbe # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c808839-d931-4c2c-8103-4c75468eaa51
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4833d0ea-ad40-464a-a8e7-5db5d76c7f2f
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: a61b30a6-e258-4588-99a7-18946b0c228a # Marathons Ch
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
