fieldLayouts:
  00ea857d-a2fa-4997-b5c8-0b7f6ec7871c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e2e11d45-78b7-4669-9746-69a8665ba44f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 40aac9d7-9827-49f3-8c21-f3afc8801788 # Common Excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 187f37b2-c0db-4c7b-82b2-3aab196fa0c6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 33cc00d2-9fab-43dc-8159-86109aec387b # Main Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 080d1767-c20d-4b8b-b9c4-77a64201bc35
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fa7b64ed-a01d-49d6-ac41-0662e5ccddbe # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d9b8c4ce-c843-4b1d-aeaf-fd17bee79be3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f7f27716-4ea7-4461-8c8a-9b450fc114bd # Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 141bb486-eb96-489a-942b-f1c469bf0fae
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: aeb1ae5f-0c06-41d1-98d2-0b5bd3ef5992
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 7db06de3-76b7-43bc-9ff1-28f8ecf767be # Nutrition Ch
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
