fieldLayouts:
  c67a1cf0-d34d-4f22-8ab4-de088ca79638:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 38f0f802-aca1-46e0-800f-e224fb4fda29
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 33cc00d2-9fab-43dc-8159-86109aec387b # Main Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a354b9d3-672f-424d-88d3-a8dd5135f1df
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 40aac9d7-9827-49f3-8c21-f3afc8801788 # Common Excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d3c5ec6-9975-44b4-9806-269e3ba6f2b9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fa7b64ed-a01d-49d6-ac41-0662e5ccddbe # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b322f541-a502-4dec-a56d-ecbcab610361
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f7f27716-4ea7-4461-8c8a-9b450fc114bd # Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5d588b20-1801-46da-a3b8-817615162398
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4f932e3a-9ba0-423e-a121-dcf871d35b7b
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: f27231f1-beef-447d-b028-5f0c7e4a9bc9 # News
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
