fieldLayouts:
  3190ff90-54b3-49da-8a7c-29e0d5247d8f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5eac90e3-7997-48c2-b669-562de0386bd5
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: fa7b64ed-a01d-49d6-ac41-0662e5ccddbe # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50f88cc9-f62d-4612-9652-1c6cf3578cb9
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 40aac9d7-9827-49f3-8c21-f3afc8801788 # Common Excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8820f0e6-4e7c-40cb-af58-53e2fc22e961
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: f7f27716-4ea7-4461-8c8a-9b450fc114bd # Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 89fefd7f-6794-49c6-b16f-b9f0356be553
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 33cc00d2-9fab-43dc-8159-86109aec387b # Main Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 680fd0c1-65ec-4535-af31-daacf56aa6d4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e4d8b426-278e-42a6-916d-704470870cdf
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: d59ab545-9736-4a2f-8e27-ecef3b589928 # Blog
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
