fieldLayouts:
  3aaffa46-fd4e-4598-aa0f-a92e63caa88f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8f174ebe-6227-46f4-9841-251f25ca7d25
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 40aac9d7-9827-49f3-8c21-f3afc8801788 # Common Excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 657eae24-ecb6-46dc-aa3a-fbeeab79bb1c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fa7b64ed-a01d-49d6-ac41-0662e5ccddbe # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 26eae452-2cb7-4214-84d4-ba48eb8c9240
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0ebb5e96-5a99-44ff-a210-25b7333fffae
        userCondition: null
handle: marathons
hasTitleField: true
name: Marathons
section: 482daefc-46cd-4e4f-b61e-45d2aa45525b # Marathons
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
