fieldLayouts:
  81f38586-430f-4894-8284-60fa983c2d40:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 99cb38d1-2ec2-4fed-af69-a35f30f92ba5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 40aac9d7-9827-49f3-8c21-f3afc8801788 # Common Excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 349d2c94-d305-4c76-ac31-2067725b615d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fa7b64ed-a01d-49d6-ac41-0662e5ccddbe # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23c095dd-ebdd-4135-8487-d637c556f2d7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e0324882-9e73-47a2-a6c0-c46c8335933e
        userCondition: null
handle: physio
hasTitleField: true
name: 'Physio Corner'
section: b6599a8c-e938-4f38-8b85-66492561d1a1 # Physio Corner
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
