fieldLayouts:
  007b00da-75a8-44b7-b879-2ba90bf4fc2a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 03dc811a-b07d-4dad-875c-c9bb1adc505e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fa7b64ed-a01d-49d6-ac41-0662e5ccddbe # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0d550eb-e4a8-476d-b03b-7233b6556fb8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 40aac9d7-9827-49f3-8c21-f3afc8801788 # Common Excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b182da1-0b43-4254-b218-a1b2b1d7aedb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 33cc00d2-9fab-43dc-8159-86109aec387b # Main Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b7d7048-a9a2-48c7-bc14-b1e07b1fb971
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: de15261c-cd31-47ac-854f-d5b7967b7c84 # HTML Field
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4dab6a28-f052-451b-b8a7-b80e9bec5d0e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7c23aef3-3cda-4bab-bf21-ce26e6e3ea93
        userCondition: null
handle: subscribe
hasTitleField: true
name: Subscribe
section: 08ad92eb-cfb5-49d4-820f-ff7da4395e4b # Subscribe
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
