defaultPlacement: end
fieldLayouts:
  5d44c8e0-283e-4376-86a7-b4ad42def065:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 9dd8f1f1-7950-4b0f-9b28-06b957a92cc8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 40aac9d7-9827-49f3-8c21-f3afc8801788 # Common Excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28d52e85-09f7-4f40-b57a-e526ff6e481c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 33cc00d2-9fab-43dc-8159-86109aec387b # Main Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f124493-d718-4478-acaa-f31f116e5b91
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fa7b64ed-a01d-49d6-ac41-0662e5ccddbe # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63aad972-1859-4f56-be0c-2151c9e2cbcc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cce249eb-41f1-408c-bf94-7b8364b1d256
        userCondition: null
handle: raceDistance
name: 'Race Distance'
siteSettings:
  e62c9b25-609e-48b9-b7a6-ad33a704654b: # Run Republic
    hasUrls: true
    template: races/test.twig
    uriFormat: 'races/{slug}'
structure:
  maxLevels: null
  uid: 05742369-4a99-442b-86c3-bbbf2afcd611
