fieldLayouts:
  335ea7ef-d582-40d9-8af0-af90c9f49211:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: f8aff2d4-979c-47c3-93df-213cea68c8b0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9613fa58-9628-436f-b7b8-05c13e43f83c
        userCondition: null
fs: uploads
handle: uploads
name: Uploads
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: /var/www/html/web
