columnSuffix: null
contentColumnType: string
fieldGroup: f0b3c4f3-fd2e-4f0c-b31b-ad26982ff05f # Races
handle: raceResults
instructions: null
name: 'Race Results'
searchable: false
settings:
  contentTable: '{{%matrixcontent_raceresults}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
