columnSuffix: sndkqhub
contentColumnType: string(255)
fieldGroup: f0b3c4f3-fd2e-4f0c-b31b-ad26982ff05f # Races
handle: raceEmail
instructions: null
name: 'Race Email'
searchable: false
settings:
  maxLength: 255
  types:
    - email
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
