columnSuffix: inuigmov
contentColumnType: string(255)
fieldGroup: 73618bf8-b226-4a8c-8870-3d5f5c1fef7a # Social Media
handle: snapchat
instructions: null
name: Snapchat
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
