columnSuffix: null
contentColumnType: string
fieldGroup: c329aeb4-d418-4b22-8f59-3a9b056de877 # HeadFoot
handle: topNav
instructions: null
name: 'Top Nav'
searchable: false
settings:
  contentTable: '{{%matrixcontent_topnav}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
