defaultPlacement: end
enableVersioning: true
handle: physioch
name: 'Physio Ch'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  e62c9b25-609e-48b9-b7a6-ad33a704654b: # Run Republic
    enabledByDefault: true
    hasUrls: true
    template: physio/_entry
    uriFormat: 'physio/{slug}'
type: channel
